### ISSUE TITLE
Support backticks

### ISSUE THREAD

**Issue by szarnyasg** [slizaa/slizaa-opencypher-xtext#11]
Cypher allows the use of backticks to escape names thus making it possible to use names with whitespaces, special characters, etc. This is also captured in the ANTLR grammar provided by the openCypher project:

```
/**
 * Any character except "`", enclosed within `backticks`. Backticks are escaped with double backticks. */
EscapedSymbolicName : ( '`' ( EscapedSymbolicName_0 )* '`' )+ ;
```

However, this is currently not supported by the Slizaa grammar: see the [`SYMBOLIC_NAME_X `](https://github.com/slizaa/slizaa-opencypher-xtext/blob/master/plugins/org.slizaa.neo4j.opencypher/src/org/slizaa/neo4j/opencypher/OpenCypher.xtext#L828) rule.

**Comment by wuetherich** [comment]
Thanks @kris7t !
