### ISSUE TITLE
Create Extract object for EXTRACT functions

### ISSUE THREAD

**Issue by szarnyasg** [slizaa/slizaa-opencypher-xtext#12]
The current Xtext grammar creates a `Filter` object for `EXTRACT` functions:

https://github.com/slizaa/slizaa-opencypher-xtext/blob/fdbfeb2509ba3fc743be7fc73930c3bb1ef620cc/plugins/org.slizaa.neo4j.opencypher/src/org/slizaa/neo4j/opencypher/OpenCypher.xtext#L679-L680

Is this on purpose, so that `EXTRACT` and `FILTER` functions can be handled similarly, or should it be like this?

```
{Extract} 'EXTRACT' '(' filterExpression=FilterExpression ('|' expression=Expression)? ')'
```

**Comment by wuetherich** [comment]
No, that's not on purpose. And yes, it should be 

`{Extract} 'EXTRACT' '(' filterExpression=FilterExpression ('|' expression=Expression)? ')'`

I will fix it.
