### ISSUE TITLE
Error message when undoing a (successful) refactoring

### ISSUE THREAD

**Issue by szarnyasg** [slizaa/slizaa-opencypher-xtext#19]
After performing a successful refactoring and invoking an undo command, I get the following error:

![screenshot from 2018-01-10 16-17-11](https://user-images.githubusercontent.com/1402801/34779897-e08ed3f2-f621-11e7-80b1-df51f7419bf1.png)

This is present in both the latest snapshot version and in 0.0.4 (at http://slizaa.org/download/index.php). Unfortunately, I have no idea why this happens.

**Comment by wuetherich** [comment]
Seems that this is a xtext related bug that is already filed: 
https://bugs.eclipse.org/bugs/show_bug.cgi?id=430398

I will check if the suggested solution fixes this issue...

**Comment by wuetherich** [comment]
Won't fix.
