### ISSUE TITLE
Minor grammar issues

### ISSUE THREAD

**Issue by szarnyasg** [slizaa/slizaa-opencypher-xtext#29]
`RangeLiterals` can accept a single bound: optionalities are skewed at.

https://github.com/slizaa/slizaa-opencypher-xtext/blob/master/plugins/org.slizaa.neo4j.opencypher/src/org/slizaa/neo4j/opencypher/OpenCypher.xtext#L490-L495

Empty `ExpressionLists` are not accepted:

https://github.com/slizaa/slizaa-opencypher-xtext/blob/master/plugins/org.slizaa.neo4j.opencypher/src/org/slizaa/neo4j/opencypher/OpenCypher.xtext#L687

**Comment by szarnyasg** [comment]
I am just about to commit the fixes, but I have a question - why do we commit the `model/generated/` folder?

**Comment by wuetherich** [comment]
For historical reasons. Something I initially made wrong and never fixed later, so now is a good moment to remove it from the repo.

**Comment by wuetherich** [comment]
In former versions I checked in all generated source files (also the src-gen and the xtend-gen folders). Later I discovered how the execute the mwe2 launcher from within maven, which made it possible to generate all required files during the CI-Build.
