### ISSUE TITLE
Promote slizaa-opencypher-xtext to its own toplevel project/repo

### ISSUE THREAD

**Issue by wuetherich** [slizaa/slizaa-opencypher-xtext#32]
The slizaa-opencypher-xtext project that currently is a sub-project of slizaa should be promoted to its own toplevel project/repo.

I already created a new toplevel github organization "https://github.com/opencypher-xtext".

**Comment by wuetherich** [comment]
I just moved the slizaa-opencypher-xtext project to 'https://github.com/code-kontor/openCyper-Xtext' (which is the repo of my company that I founded last year). I also changed the namespace of all components from 'org.slizaa.xtext.opencypher' to 'io.codekontor.opencypher.xtext'. 

I will 'close' this repo, so future development will happen exclusively in the mentioned new repository (and under the new namespace).

@szarnyasg note that the changes for M12 are already committed and pushed to the new location

**Comment by szarnyasg** [comment]
@wuetherich great, thanks for letting us know.

Did you consider
- adding a link to the README to the new location and
- [archiving this repository](https://help.github.com/articles/archiving-repositories/)?

**Comment by szarnyasg** [comment]
Also, there is a typo in the name of the repository - `openCyper` instead of `openCypher`

**Comment by wuetherich** [comment]
argh ;-) it was too late in the evening. I corrected the name, so the new repo location is https://github.com/code-kontor/openCypher-Xtext.
