### ISSUE TITLE
Unbounded index expression parse error

### ISSUE THREAD

**Issue by jmarton** [slizaa/slizaa-opencypher-xtext#34]
While both of the examples below are correct in openCypher, the 2nd and 3rd yields a parse error.

```
RETURN range(0,10)[2..5]
;
RETURN range(0,10)[2..] // results in  no viable alternative at input ']'
; 
RETURN range(0,10)[..5] // no viable alternative at input '..'
;
```

This is the corresponding excerpt from the M09-rewrite (#23) from the grammar.

https://github.com/slizaa/slizaa-opencypher-xtext/blob/76bbbb501ac26a10900b7189792ef4d9829e0e8c/plugins/org.slizaa.neo4j.opencypher/src/org/slizaa/neo4j/opencypher/OpenCypher.xtext#L739-L743

**Comment by wuetherich** [comment]
I just committed a fix for the oC_StringListNullOperatorExpression. Unfortunately, I can't run any tests currently as 'OpenCypherScopeProvider.xtend' still has compile errors. May you find some time to fix this?

**Comment by szarnyasg** [comment]
Hey @wuetherich, I can find some time to work in this later in the week, but as I wrote in https://github.com/slizaa/slizaa-opencypher-xtext/issues/23#issuecomment-364757189, there are some issues in the M09 grammar that prevent valid expressions from bein parsed. @jmarton 's proposed some (surprisingly complex) grammar changes in https://github.com/opencypher/openCypher/pull/300. If these get merged to openCypher and we follow those, that would break the scope code again.

**Comment by wuetherich** [comment]
ah ok, i missed this ;-) so, there won't be a slizaa-opencypher-xtext release for the M09 grammar and we proceed to work on it once the M10 grammar is released?

**Comment by szarnyasg** [comment]
Yes, I think it would make sense to skip M06...M09 because the changes to enforce a more strict clause structure (introduced in https://github.com/opencypher/openCypher/commit/3702d2eeb17380a2291c667c7c92072eb96253cc) break some otherwise valid queries.
