### ISSUE TITLE
CREATE UNIQUE does not work

### ISSUE THREAD

**Issue by szarnyasg** [slizaa/slizaa-opencypher-xtext#44]
`CREATE UNIQUE` does not work, which causes some of the [jQAssistant test queries](https://github.com/slizaa/slizaa-opencypher-xtext/blob/fa09397535b1667046113f12d8c9b98b4b6a5c17/tests/org.slizaa.neo4j.opencypher.tests/src/org/slizaa/neo4j/opencypher/external/tests/jqaconcepts/JQAssistantConcepts.xtend) to fail:

```
java.lang.AssertionError: Expected no errors, but got :ERROR (org.eclipse.xtext.diagnostics.Diagnostic.Syntax) 'missing '=' at '('' on NodePattern, offset 14, length 1
```

It seems the Xtext grammar does not support `CREATE UNIQUE`. The rule is there:

https://github.com/slizaa/slizaa-opencypher-xtext/blob/fa09397535b1667046113f12d8c9b98b4b6a5c17/plugins/org.slizaa.neo4j.opencypher/src/org/slizaa/neo4j/opencypher/OpenCypher.xtext#L300-L304

But `UniqueConstraint` is actually related to unique constraint and not the `UNIQUE` keyword for `CREATE`:

https://github.com/slizaa/slizaa-opencypher-xtext/blob/fa09397535b1667046113f12d8c9b98b4b6a5c17/plugins/org.slizaa.neo4j.opencypher/src/org/slizaa/neo4j/opencypher/OpenCypher.xtext#L225-L230

Checking the blame history, this commit is responsible for the related change: https://github.com/slizaa/slizaa-opencypher-xtext/commit/823e0b5afd1013d5a58ec142b8281d2b5c4c9c10#diff-07ac65c561c15a3080a682e20e19c5aeL260

**Comment by wuetherich** [comment]
fixed with https://github.com/slizaa/slizaa-opencypher-xtext/commit/bb93b2c5442d93cd559b464f27b5f3877e8d7b3d
