### ISSUE TITLE
Track changes in the openCypher grammar for M12 and beyond

### ISSUE THREAD

**Issue by szarnyasg** [slizaa/slizaa-opencypher-xtext#49]
See the history of the grammar: https://github.com/opencypher/openCypher/commits/master/grammar

M12 contained the changes in PR https://github.com/opencypher/openCypher/pull/324
However, this was later amended with PR https://github.com/opencypher/openCypher/pull/339, so it'd make sense to apply these to Slizaa two in a single step.

The only other change is https://github.com/opencypher/openCypher/commit/cefaa6f27678c1940dec75e923577de7056f3058#diff-b3d1bd6a249a6a85c42bc5762cec6e1f.

**Comment by wuetherich** [comment]
I implemented the changes for M12 and pushed it to the new repo location at https://github.com/code-kontor/openCyper-Xtext.
(see https://github.com/slizaa/slizaa-opencypher-xtext/issues/32)

**Comment by wuetherich** [comment]
This will be done in the new repo located at https://github.com/code-kontor/openCypher-Xtext.
