### ISSUE TITLE
Usage scenarios / abandon Eclipse IDE support?

### ISSUE THREAD

**Issue by wuetherich** [slizaa/slizaa-opencypher-xtext#50]
Currently, the openCypher-Xtext project provides bundles and features that can be installed and executed in an Eclipse IDE and/or an RCP application. 

As the Xtext framework now also supports the creation of Language Servers and Web-Clients, it eventually makes sense to abandon the Eclipse Plugin support and provide maven artifacts instead of eclipse plugins. This would allow me to deploy the maven artifacts directly to maven central. 

@szarnyasg I have nearly no idea how do you use the openCypher-Xtext implementation. Do you need the eclipse support or do you just use the parser to create the AST?

My goal is to deploy openCypher-Xtext artifacts together with working POMs to maven central - it would be a trivial task if I abandon the Eclipse support and switch to a maven project setup...

**Comment by szarnyasg** [comment]
@wuetherich - we are only using the parser component, so an artifact
without Eclipse support works for our use case.

Thanks for considering us during the refactoring!
